# Generated by Django 4.2 on 2025-12-28 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BahanBaku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_bahan', models.CharField(max_length=20, unique=True, verbose_name='Kode Bahan')),
                ('nama_bahan', models.CharField(max_length=100, verbose_name='Nama Bahan')),
                ('kategori', models.CharField(choices=[('karbohidrat', 'Sumber Karbohidrat'), ('hewan', 'Protein Hewani'), ('nabati', 'Protein Nabati'), ('sayur', 'Sayur'), ('buah', 'Buah'), ('lemak', 'Sumber Lemak'), ('susu', 'Susu'), ('bumbu', 'Bumbu & Pelengkap')], max_length=50, verbose_name='Kategori')),
                ('satuan_dasar', models.CharField(choices=[('gr', 'Gram (g)'), ('kg', 'Kilogram (kg)'), ('ml', 'Mililiter (ml)'), ('liter', 'Liter (l)'), ('pcs', 'Pcs/Buah'), ('ikat', 'Ikat'), ('butir', 'Butir'), ('pack', 'Pack/Bungkus'), ('sisir', 'Sisir')], default='gr', max_length=20, verbose_name='Satuan Dasar')),
                ('estimasi_harga', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Estimasi Harga')),
                ('masa_simpan', models.IntegerField(default=0, verbose_name='Masa Simpan (Hari)')),
            ],
            options={
                'verbose_name': 'Bahan Baku',
                'verbose_name_plural': 'Daftar Bahan Baku',
            },
        ),
        migrations.CreateModel(
            name='RencanaMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(verbose_name='Tanggal Penyajian')),
            ],
            options={
                'verbose_name': 'Rencana Menu Harian',
                'verbose_name_plural': 'Daftar Rencana Menu Harian',
            },
        ),
        migrations.CreateModel(
            name='Resep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_masakan', models.CharField(max_length=100, verbose_name='Nama Masakan')),
                ('kategori_masakan', models.CharField(choices=[('karbohidrat', 'Sumber Karbohidrat'), ('hewan', 'Protein Hewani'), ('nabati', 'Protein Nabati'), ('sayur', 'Sayur'), ('buah', 'Buah'), ('susu', 'Susu')], max_length=50, verbose_name='Kategori Masakan')),
            ],
            options={
                'verbose_name': 'Resep Masakan',
                'verbose_name_plural': 'Daftar Resep Masakan',
            },
        ),
        migrations.CreateModel(
            name='StandarGizi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kelompok_sasaran', models.CharField(max_length=100, verbose_name='Kelompok Sasaran')),
                ('waktu_makan', models.CharField(choices=[('pagi', 'Makan Pagi'), ('siang', 'Makan Siang'), ('kudapan', 'Makanan Tambahan/Kudapan')], max_length=50, verbose_name='Waktu Makan')),
                ('pagu_belanja', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Pagu Belanja Per-Porsi (Rp)')),
                ('rujukan_akg', models.CharField(max_length=100, verbose_name='Rujukan AKG (%)')),
                ('energi_min', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Energi Minimal (Kkal)')),
                ('energi_max', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Energi Maksimal (Kkal)')),
                ('protein_min', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Protein Minimal (g)')),
                ('protein_max', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Protein Maksimal (g)')),
                ('lemak_min', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Lemak Minimal (g)')),
                ('lemak_max', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Lemak Maksimal (g)')),
                ('karbo_min', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Karbohidrat Minimal (g)')),
                ('karbo_max', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Karbohidrat Maksimal (g)')),
            ],
            options={
                'verbose_name': 'Standar Gizi & Biaya',
                'verbose_name_plural': 'Standar Gizi & Biaya',
                'unique_together': {('kelompok_sasaran', 'waktu_makan')},
            },
        ),
        migrations.CreateModel(
            name='RencanaMenuDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rencana_menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='perencanaan.rencanamenu', verbose_name='Rencana Menu')),
                ('resep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perencanaan.resep', verbose_name='Nama Masakan')),
            ],
            options={
                'verbose_name': 'Isi Menu/Resep',
                'verbose_name_plural': 'Isi Menu/Resep',
            },
        ),
        migrations.AddField(
            model_name='rencanamenu',
            name='standar_gizi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perencanaan.standargizi', verbose_name='Sasaran & Waktu Makan'),
        ),
        migrations.CreateModel(
            name='KonversiSatuan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_satuan', models.CharField(max_length=50, verbose_name='Nama Satuan (Ikat/Pcs/Butir)')),
                ('nilai_gram', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Nilai Gram per Satuan')),
                ('bahan_baku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='konversi_satuan', to='perencanaan.bahanbaku', verbose_name='Bahan Baku')),
            ],
            options={
                'verbose_name': 'Konversi Satuan',
                'verbose_name_plural': 'Daftar Konversi Satuan',
            },
        ),
        migrations.CreateModel(
            name='KandunganGizi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('energi', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Energi (Kkal)')),
                ('protein', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Protein (g)')),
                ('lemak', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Lemak (g)')),
                ('karbohidrat', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Karbohidrat (g)')),
                ('persen_bdd', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Berat Dapat Dimakan (%)')),
                ('bahan_baku', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kandungan_gizi', to='perencanaan.bahanbaku', verbose_name='Bahan Baku')),
            ],
            options={
                'verbose_name': 'Kandungan Gizi',
                'verbose_name_plural': 'Daftar Kandungan Gizi',
            },
        ),
        migrations.CreateModel(
            name='BahanResep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('berat_gram', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Berat Bersih (gr)')),
                ('jumlah_satuan', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Jumlah Satuan')),
                ('bahan_baku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perencanaan.bahanbaku', verbose_name='Bahan Baku')),
                ('resep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='komposisi', to='perencanaan.resep', verbose_name='Resep')),
                ('satuan_konversi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='perencanaan.konversisatuan', verbose_name='Satuan Konversi')),
            ],
            options={
                'verbose_name': 'Komposisi Bahan',
                'verbose_name_plural': 'Komposisi Bahan',
            },
        ),
        migrations.AlterUniqueTogether(
            name='rencanamenu',
            unique_together={('tanggal', 'standar_gizi')},
        ),
    ]
