# Generated by Django 4.2 on 2025-12-28 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perencanaan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='konversisatuan',
            name='bahan_baku',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='konversi_satuan', to='perencanaan.bahanbaku', verbose_name='Bahan Baku'),
        ),
    ]
