"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Load .env file
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-default-key')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', '').split(',') if os.getenv('ALLOWED_HOSTS') else []


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'perencanaan',
    
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.getenv('DB_NAME', 'scm_sppg_db'),
        'USER': os.getenv('DB_USER', 'root'),
        'PASSWORD': os.getenv('DB_PASSWORD', ''),
        'HOST': os.getenv('DB_HOST', '127.0.0.1'),
        'PORT': os.getenv('DB_PORT', '3306'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    # {
    #     'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    # },
    # {
    #     'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    # },
    # {
    #     'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    # },
    # {
    #     'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    # },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'id-id'

TIME_ZONE = 'Asia/Jakarta'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# config/settings.py (Tambahkan di bagian paling bawah)

JAZZMIN_SETTINGS = {
    # == Judul & Header ==
    "site_title": "SCM SPPG Admin",
    "site_header": "SCM SPPG",
    "site_brand": "System SCM",
    "welcome_sign": "Selamat Datang di Panel Admin SCM SPPG",
    "copyright": "SPPG XXX",
    "search_model": ["auth.User", "auth.Group"],
    "user_avatar": None, # "profile_photo" (nama field di model User)

    # == Navigasi Atas (Top Menu) ==
    "topmenu_links": [
        {"name": "Home",  "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": "Support", "url": "https://google.com", "new_window": True},
        # Contoh Dropdown di Atas:
        # {"name": "Laporan", "links": [
        #     {"name": "Laporan Bulanan", "url": "/admin/laporan-bulan/"},
        #     {"name": "Laporan Tahunan", "url": "/admin/laporan-tahun/"},
        # ]},
    ],

    # == Sidebar (Menu Samping) ==
    "show_sidebar": True,
    "navigation_expanded": False, # Set ke False agar menu menjadi dropdown (tidak terbuka otomatis)
    
    # Custom links untuk app tertentu
    "custom_links": {
        "auth": [
            # {"name": "Audit Log", "url": "admin:index", "icon": "fas fa-history", "permissions": ["auth.view_user"]},
        ],
    },

    # Ikon untuk App dan Model (Font Awesome)
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        # --- Daftar Ikon SCM & Umum (Tinggal Copy-Paste) ---
        # Master Data:  fas fa-database, fas fa-layer-group, fas fa-table
        # Pengguna:     fas fa-user-tie, fas fa-user-shield, fas fa-users
        # Logistik:     fas fa-truck, fas fa-shipping-fast, fas fa-boxes
        # Gudang:       fas fa-warehouse, fas fa-pallet, fas fa-inventory
        # Keuangan:     fas fa-money-bill-wave, fas fa-file-invoice-dollar
        # Laporan:      fas fa-chart-line, fas fa-file-alt, fas fa-print
        # Keranjang/Order: fas fa-shopping-cart, fas fa-clipboard-list
        # Lokasi:       fas fa-map-marker-alt, fas fa-city
        # Alat/Setting: fas fa-cogs, fas fa-tools, fas fa-wrench
    },

    # Urutan Menu
    "order_with_respect_to": ["auth", "books", "orders"],

    # Sembunyikan App/Model tertentu
    # "hide_apps": ["auth"],
    # "hide_models": ["auth.user"],

    "site_logo_classes": "img-circle",
}

JAZZMIN_UI_TWEAKS = {
    # == Gaya Sidebar ==
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": True, # Indentasi menu anak (lebih rapi untuk dropdown)
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,

    # == Tema (Pilih satu yang aktif) ==
    "theme": "superhero", # Tema gelap (Aktif)
    # "theme": "flatly",   # Tema terang & bersih
    # "theme": "darkly",   # Tema gelap lainnya
    # "theme": "pulse",    # Tema ungu cerah
    # "theme": "sandstone",
    
    # == Warna Elemen ==
    "navbar": "navbar-dark",
    "sidebar": "sidebar-dark-warning",
    "accent": "accent-warning",
    
    # == Pengaturan Body ==
    "no_navbar_border": True,
    "body_small_text": False,
    "brand_small_text": False,
    "footer_fixed": False,
    "footer_small_text": True,
}
